# Generated by Django 6.0.5 on 2026-06-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_guitar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
